path: C:\Users\josea\Documents\Luis Adrian\CubeRT_Cubesat\Software\Machine_Learning_Solutions
train: C:\Users\josea\Documents\Luis Adrian\Moon_Dataset\Corrected_Augmented_Dataset\train\images
val: C:\Users\josea\Documents\Luis Adrian\Moon_Dataset\Corrected_Augmented_Dataset\valid\images

# Classes

names:
  0: Moon